### PR TITLE
fix for styling issue on dropDown component and added small class for buttons component

### LINKED ISSUE #58: fix dropDown component

### PR DESCRIPTION
**Pull request by brandonk1234**
fixes #58

### CODE REVIEW

**Comment by brandonk1234** [comment]
+1

File: src/container.js [hunk 1]
```diff
@@ -229,7 +229,8 @@ var Container = React.createClass({
                     <Button disabled={true} className="primary" text="Disabled Button" onClick={this.onClick}/>
                     <Button text="Large Primary Button" className="primary large" onClick={this.onClick}/>
                     <Button icon="arrow-left" onClick={this.onClick} toolTip="oh yes primary"/>
-                    <Button icon="star" text="full width button" onClick={this.onClick} className="primary full-width"/>
+                    <Button icon="star" text="full width button" onClick={this.onClick} className="primary full-width" _isSmall={true}/>
```
Comment (darylhedley) [inline src/container.js]: @brandonk1234 don't like the _ on the props - could you change this to isSmall

**Comment by darylhedley** [comment]
+1
